language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: kzBy3BFW36VC1cFIyHwHObj4rFek6TeLSNVzbwqSVVbHpGjPbty9YEs70N+R1blzFr7jNCk/MHeLUbb9nXWFf4SV74iUTMQxyIqCethZSKhOC1RfuuXhDFRGHqQ8yAlyHlw5cEaOpz/q1W3LhdB9c052iQMPMnk27DNoY7+Pl1VuuXYDkdQBoRZYfNoPVbyEz+pRvIsPOKbVW1wPI8pvTwSquYRzonS21CcGhWr3VcSNMXw6mEyouP86acC0dB1A5To35VDjLFzCMtIUpFF8PQ1vg+BfpZWFcljJUpxTi6ewQb56B/j2EZdMNIkPk8poJGHYtDmpbIXflhdP11hSryzCEszvTzWX/GbcC5814YtDwZKtPXLLkSGUMX76b/W1mDlK6gOHSNOPsJweQ8ohjl0It2kaCdmLMKCY+rtt5jK5OKG6Vhyn44cqjtP2VtHoZVTZ5xKmdWwxVpBSceACdyL10bTGLmbp6UkdVslei+3kU6U2ZYxGQo93Cjtm34BTB8ohDe+ojdUwHFo/rLBNcb7JY7iP1iKxPdyzPmJdYagFZnWibHJgeSKMLgzxJCGynlEgxjNaQIfkrfjdd5gSfch3iXOaF5nBgFV8n0kCIKyDGdj4/s6OqgP5Mjg1DOVfQZQ4xNmGVZ7MJ6J/ATzQrhxp/eu9+NRefZtoLMkvGe4=
  app: todo-backend
  on:
    branch: test_deployment