language: node_js
node_js:
- '16'
cache:
  directories:
  - node_modules
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: g8J9keRP+vGTIbVW4ykf1xa/x66ju3yclhOLcRBPIT2varEMvgyyYNJ5YqBNxsS913Z2BodqzKpOJcTnUl1vvdciqLH24O+GA/RX5B2Ze0l5Vn6Lag0L10bVckCO2mYga+MqUi1xdWw46WW1Sa+TxiLjmDJ8LX1M2NOJOJdoUHiqEO2EnP030a1NVh7q/LRBWOxEbxQMZwZM3FDXLptT/2f8V7lviffAEhn5Fe7NLUumTIfmBwFUBQig4Xz6fOCOfghsIV64gnJnhnTFiEe0yN2zZwAc6kY+YWUsdJQLH8cJG+7TqFz9If+oXpcOqI7u+G0fUIBH+bqnSX5hCqAKJ4LTZ/Nj3UK4PGED+5fT9kEhAV6QmgXtXqK09+VYqhHVmuJVp+A5ULIENG8Q7jcAt2ewR+0PY7LovLMPGEhMynVRTG5XHoBXJgUMcvRgHJYAD1jCUPj9fqcV4zVCcHMT53siuZB/t/8xHZlL+F9yLGiNmITHH+0jT824FbOe/RrYjifUoHbnPX2Lzhu9YBEJipS6b1/PSDu9cXCJHz9ouTlzKFB+UamSte5lg8PQyPmlYUHow1PKQXJMCyxIAqNgKycrOVO92UcZVHgSqFWHHll4Nlh7a3v1pjc00QVQVfT4OwyYTAJS+sESdkxT5xsMQ+8vX0kUbHIJU5AxwlNl1sg=
  app: todo-backend
  on:
    branch: test_deployment