language: node_js
node_js:
- '16'

env:
  global:
    secure: AphJ14zaYq8VWVrmbiDF77OZhUK659Q/HErPH0FgcGn0AMrAeWR3qARIRg7qr4ZKnriO/YttqnyMsPOipOjXc+Y6eS7Gxu/oWtrSH0/rHGGhXSxaz16T1rf/ErXzBm175foAKnZouGeO8tQoHFfVikhbMbt2lbaHfXj/MaE1WMK8kdP0EvLs1OgLyOhXsJmJaujER7rTIO0l7nTqPCLKeCr2ql4hqdksmzo/f+tfyjU/m1d+dEFkbglUJMyfS+F37c72x9kXt69R37YjeA51zO3hhFfGoiqnU7Hi0qpJ8OL7vKDiMEbLGSFea4s6ErBHwMKzVV5aRNQCt4SQXGNC8SQX3PMdwak3qBq2vTwQaMAoxUUS0hgwqfIv5vXjObIeVBcjY6AUlGk96A1kvprZrllye3QMGiQPOKlAfKUPgoJ7hUOsGYM/BRIK3sFRDNAoiiGrsbwLl6hkH0jbeqONijGRCCOzsUXBwEil3x/6w0rATNgf/lgDA8oJepAVFhfKaApXIW+45s3QI0NxxjCTXNrPtnAvI0iTlCrPFSyLD8FxYlteic8GkQ6OAipyhWi57lZBuOgrRPwtfhMtcTbFn6UnDJGiqbmGf25NjuO0nvI6NHC1vFBXHa3F9IlYoR0LaQrhQdJ7Jkzj1LITjais+rIcT0qXvCnpUJ/yPeeVU4E=

cache:
  directories:
  - node_modules

before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
  app: todo-backend
  on:
    branch: test_deployment
